---
- name: Setup localhost
  hosts: localhost
  tasks:
    - name: Enable starship COPR
      become: true
      ansible.builtin.command: dnf copr enable -y chronoscrat/starship
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:chronoscrat:starship.repo
      tags: always

    - name: Install common packages
      become: true
      ansible.builtin.package:
        name:
          - bat
          - btop
          - emacs
          - fzf
          - google-roboto-mono-fonts
          - just
          - starship
        state: present
      tags: always

    - name: Install home packages
      become: true
      ansible.builtin.package:
        name:
          - vorta
          - shotwell
        state: present
      tags: home

    - name: Symlink dotfiles
      ansible.builtin.file:
        src: '{{ playbook_dir }}/{{ item }}'
        dest: '{{ ansible_env.HOME }}/{{ item }}'
        state: link
      loop:
        - .bashrc.d
        - .emacs.d
        - .gitexcludes
        - .config/git
      tags: always

    - name: Symlink Git user config
      ansible.builtin.file:
        src: '{{ playbook_dir }}/.config/git/user-config.{{ ansible_run_tags | first }}'
        dest: '{{ playbook_dir }}/.config/git/user-config'
        state: link
      tags:
        - home
        - work

    - name: Enable niri COPR
      become: true
      ansible.builtin.command: dnf copr enable -y yalter/niri
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:yalter:niri.repo
      tags: niri

    - name: Install Niri and related packages
      become: true
      ansible.builtin.package:
        name:
          - niri
          - swaybg
          - mako
          - kanshi
          - pavucontrol
          - network-manager-applet
        state: present
      tags: niri

    - name: Create .config/systemd/user/niri.service.wants
      ansible.builtin.file:
        path: '{{ ansible_env.HOME }}/.config/systemd/user/niri.service.wants'
        state: directory
      tags: niri

    - name: Symlink Niri configuration
      ansible.builtin.file:
        src: '{{ playbook_dir }}/.config/{{ item }}'
        dest: '{{ ansible_env.HOME }}/.config/{{ item }}'
        state: link
      loop:
        - kanshi
        - niri
        - waybar
        - systemd/user/swaybg.service
      tags: niri

    - name: Setup Niri wants
      ansible.builtin.file:
        src: '{{ item }}'
        dest: '{{ ansible_env.HOME }}/.config/systemd/user/niri.service.wants/{{ item | basename }}'
        state: link
      loop:
        - /usr/lib/systemd/user/kanshi.service
        - /usr/lib/systemd/user/mako.service
        - '{{ playbook_dir }}/.config/systemd/user/swaybg.service'
        - /usr/lib/systemd/user/waybar.service
      tags: niri

    - name: Reload systemd user session
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user
      tags: niri
